# Generated by Django 3.1.5 on 2021-02-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resourcetitle',
            new_name='resourcename',
        ),
    ]
